// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func SuccessToast(msg string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_SuccessToast_215f`,
		Function: `function __templ_SuccessToast_215f(msg){Toastify({
  text: msg,
  duration: 2500,
  destination: "/", // destination when clicked
  newWindow: false, // open destination in new window 
  close: false, // close icon button
  gravity: "top", // ` + "`" + `top` + "`" + ` or ` + "`" + `bottom` + "`" + `
  position: "right", // ` + "`" + `left` + "`" + `, ` + "`" + `center` + "`" + ` or ` + "`" + `right` + "`" + `
  stopOnFocus: true, // Prevents dismissing of toast on hover
  style: {
    background: "linear-gradient(90deg, rgba(17,117,5,1) 10%, rgba(84,196,93,1) 91%)",
  },
  onClick: function(){} // Callback after click
}).showToast();
}`,
		Call:       templ.SafeScript(`__templ_SuccessToast_215f`, msg),
		CallInline: templ.SafeScriptInline(`__templ_SuccessToast_215f`, msg),
	}
}

func DangerToast(msg string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_DangerToast_3532`,
		Function: `function __templ_DangerToast_3532(msg){Toastify({
  text: msg,
  duration: 2500,
  destination: "/", // destination when clicked
  newWindow: false, // open destination in new window 
  close: false, // close icon button
  gravity: "top", // ` + "`" + `top` + "`" + ` or ` + "`" + `bottom` + "`" + `
  position: "right", // ` + "`" + `left` + "`" + `, ` + "`" + `center` + "`" + ` or ` + "`" + `right` + "`" + `
  stopOnFocus: true, // Prevents dismissing of toast on hover
  style: {
    background: "linear-gradient(90deg, rgba(255,0,0,1) 10%, rgba(218,83,138,1) 91%)",
  },
  onClick: function(){} // Callback after click
}).showToast();
}`,
		Call:       templ.SafeScript(`__templ_DangerToast_3532`, msg),
		CallInline: templ.SafeScriptInline(`__templ_DangerToast_3532`, msg),
	}
}
