// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Toast(msg string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Toast_5b21`,
		Function: `function __templ_Toast_5b21(msg){Toastify({
  text: msg,
  duration: 2500,
  destination: "/", // destination when clicked
  newWindow: false, // open destination in new window 
  close: false, // close icon button
  gravity: "top", // ` + "`" + `top` + "`" + ` or ` + "`" + `bottom` + "`" + `
  position: "right", // ` + "`" + `left` + "`" + `, ` + "`" + `center` + "`" + ` or ` + "`" + `right` + "`" + `
  stopOnFocus: true, // Prevents dismissing of toast on hover
  style: {
    background: "linear-gradient(90deg, rgba(34,19,73,1) 20%, rgba(99,63,128,1) 100%, rgba(65,235,255,1) 100%)",
  },
  onClick: function(){} // Callback after click
}).showToast();
}`,
		Call:       templ.SafeScript(`__templ_Toast_5b21`, msg),
		CallInline: templ.SafeScriptInline(`__templ_Toast_5b21`, msg),
	}
}
