// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package public

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func IndexCss() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/css\">\n\t\tp {\n\t\t\tfont-family: sans-serif;\n\t\t}\n\t\t.simpleButton {\n\t\t\tbackground-color: green;\n\t\t\tcolor: white;\n\t\t\tborder: solid 1px black;\n\t\t\tborder-radius: 5px;\n\t\t\tpadding: 5px;\n\t\t\tcursor: pointer;\n\t\t\t\n\t\t}\n\t\t.simpleButtonRED {\n\t\t\tbackground-color: red;\n\t\t\tcolor: white;\n\t\t\tborder: solid 1px black;\n\t\t\tborder-radius: 5px;\n\t\t\tpadding: 5px;\n\t\t\tcursor: pointer;\n\t\t\t\n\t\t}\n\t\t.simpleButtonRED:hover {\n\t\t\tbackground-color: darkred;\n\t\t}\n\t\t.simpleButton:hover {\n\t\t\tbackground-color: lightgreen;\n\t\t}\n\n\t\t.simpleInput {\n\t\t\tborder: solid 1px black;\n\t\t\tborder-radius: 5px;\n\t\t\tpadding: 5px;\n\t\t\tmargin-bottom: 5px;\n\t\t\twidth: 100%;\n\t\t}\n\n\t\t.formContainer {\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\twidth: 300px;\n\t\t\tjustify-content: center;\n\t\t\tpadding: 10px;\n\t\t}\n\n\t\t.navContainer {\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t\tflex-direction: row;\n\t\t\tbackground-color: #333;\n\t\t\tcolor: white;\n\t\t\tpadding: 5px;\n\t\t}\n\t\t.navContainer a {\n\t\t\tcolor: white;\n\t\t\ttext-decoration: none;\n\t\t\tcursor: pointer;\n\t\t}\n\t\t.navContainer a:hover {\n\t\t\ttext-decoration: underline;\n\t\t}\n\t\t.nav-ol-left {\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t\twidth: 200px;\n\t\t}\n\t\t.nav-ol-right {\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: flex-end;\n\t\t\twidth: 200px;\n\t\t}\n\t\t.nav-list {\n\t\t\tlist-style-type: none;\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t\twidth: 100px;\n\t\t}\n\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
